version: '3.8'
services:
  frontend:
    container_name: frontend
    environment:
      APP_ENV: ${APP_ENV:-development}
    build: 
      context: .
      target: ${APP_ENV:-development}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: always
    volumes:
      - "./:/home/node/app:rw"
      - "/home/node/app/node_modules"
      - "/home/node/app/.next"
    networks:
      default:
        aliases:
          - frontend

networks:
  default:
    name: senpaislist-network