version: '3.8'
services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - "./:/home/node/app:rw"
      - "/home/node/app/node_modules:rw"
    networks:
      default:
        aliases:
          - frontend

networks:
  default:
    name: senpaislist-network